<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_nc_gateway']['type']['form_pdf']	= 'PDF print';
$GLOBALS['TL_LANG']['tl_nc_gateway']['file_name'][0]		= 'Filename';
$GLOBALS['TL_LANG']['tl_nc_gateway']['file_name'][1]		= 'Please enter a filename';
$GLOBALS['TL_LANG']['tl_nc_gateway']['form_pdf_save'][0]	= 'Save file';
$GLOBALS['TL_LANG']['tl_nc_gateway']['form_pdf_save'][1]	= 'Choose here to save the file and do not send it to the browser.';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_nc_gateway']['form_pdf_legend']		= 'PDF Settings';
