<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_nc_gateway']['type']['form_pdf']	= 'PDF Druck';
$GLOBALS['TL_LANG']['tl_nc_gateway']['file_name'][0]		= 'Dateiname';
$GLOBALS['TL_LANG']['tl_nc_gateway']['file_name'][1]		= 'Bitte geben Sie einen Dateinamen ein. (Inserttags sind erlaubt)';
$GLOBALS['TL_LANG']['tl_nc_gateway']['form_pdf_save'][0]	= 'Datei speichern';
$GLOBALS['TL_LANG']['tl_nc_gateway']['form_pdf_save'][1]	= 'Wählen Sie hier, um die Datei zu speichern und nicht direkt an den Browser zu senden.';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_nc_gateway']['form_pdf_legend']		= 'PDF Einstellungen';
